### ISSUE TITLE
Formatting packages

### ISSUE THREAD

**Issue by jankrynauw** [mobalti/jetbrains-new-dark#1]
Nice work on this theme!

Looking at an example from Goland (using their new dark theme):

![Screenshot 2023-11-03 at 09 38 54](https://github.com/mobalti/jetbrains-new-dark/assets/18016598/5fd6e9fb-572f-42d4-96be-98cc0392bf3c)

compared to the same code using your VS Code theme: 

![Screenshot 2023-11-03 at 09 38 40](https://github.com/mobalti/jetbrains-new-dark/assets/18016598/9bac9b09-116c-4558-9962-81140ceeaaa3)

Is there way make this similar to Goland - i.e. the packages (iampb, context) and types (Context, GetIamPolicyRequest, Policy) have different colors?  Having all in white is not as clear as how Goland does it.

**Comment by jankrynauw** [comment]
Sorted. Needed to add the following to my settings to enable gopls semantic versioning:
```
"gopls": {
    "ui.semanticTokens": true,
    "formatting.gofumpt": true,
    "codelenses": {
      "gc_details": true,
    },
  },
```

**Comment by mobalti** [comment]
Great! I aim to keep this extension in sync with VSCode's default syntax highlighting. Instead of striving for an exact replica, this approach ensures there won't be any lack of syntax highlighting in the future. With this strategy, we get the best of both worlds: VSCode's syntax highlighting for all languages and JetBrains' New Dark Color Scheme.
